accounts/urls.py
from django.urls import path

from .views import index, logout_account

app_name = 'accounts'

urlpatterns = [
  path('', index, name='login-page'),
  path('logout/', logout_account, name='logout'),
]

dj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

from app.views import error_page

import debug_toolbar

handler404 = error_page(404)
handler500 = error_page(500)

urlpatterns = [
  path('', include('social_django.urls', namespace='social')),
  path('logout/', LogoutView.as_view(template_name=settings.LOGOUT_REDIRECT_URL), name='logout'),

  path('', include('toolsframe.urls', namespace='toolsframe')),
  path('t/', include('tools.urls', namespace='tools')),
  path('account/', include('accounts.urls', namespace='accounts')),

  path('admin/', admin.site.urls),
  path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toolsframe/urls.py
from django.urls import path

from .views import index, get_tool_page, SuggestTool, ReportToolIssue, toggle_color_mode, refresh_tools, PrivacyPolicyView

app_name = 'toolsframe'

urlpatterns = [
  path('refresh/', refresh_tools, name='xxx'),

  path('', index, name='homepage'),
  path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),

  path('toggle-color-mode/', toggle_color_mode, name='toggle-color'),
  path('tool/<str:tool_id>/', get_tool_page, name='tool'),
  path('suggest-tool/', SuggestTool.as_view(), name='suggest-tool'),
  path('report-tool/<str:tool_id>/', ReportToolIssue.as_view(), name='report-tool')
]

toolsframe/models.py
import importlib
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.text import slugify

from utils import emoji
from utils.mixins import OptimizeImageField

import secrets

from .managers import  (
  UpcomingToolManager,
  ToolManager
)

User = get_user_model()

class Category(models.Model):
  name = models.CharField(max_length=128)

  created = models.DateField(auto_now_add=True)
  updated = models.DateField(auto_now=True)

  class Meta:
    verbose_name = 'Category'
    verbose_name_plural = 'Categories'

  def __str__(self):
    return self.name

  @property
  def tools(self):
    return self.category_tools.all()


class Tool(models.Model):
  LOGO_MINIMUM_DIMENSION = 170
  # required
  name = models.CharField(max_length=128)
  app_type = models.CharField(max_length=32) # api || web based
  tool_id = models.CharField(max_length=128, unique=True, editable=False, blank=True, db_index=True)
  logo = models.ImageField(upload_to='tool_logo', blank=True, null=True)
  description = models.TextField(blank=True, null=True) # SEO && after title
  url_reverser = models.CharField(max_length=64, default='toolsframe:tool') # 'app_name:home'
  endpoints = models.JSONField(blank=True, null=True)
  manager_class = models.CharField(max_length=64, blank=True, null=True)

  category = models.ManyToManyField(Category, related_name='category_tools')

  login_required = models.BooleanField(default=False)
  active = models.BooleanField(default=True, db_index=True)
  has_db = models.BooleanField(default=False)

  uses_count = models.IntegerField(default=0)
  views_count = models.IntegerField(default=0)

  created = models.DateField(auto_now_add=True)
  updated = models.DateField(auto_now=True)

  objects = ToolManager()

  class Meta:
    verbose_name = 'Tool'
    verbose_name_plural = 'Tools'

  def __str__(self):
    status = emoji.ACTIVE if self.active else emoji.DISABLE
    return f'{self.pk}- {self.tool_id} {status}{" | NoImage" if not self.logo else ""}'

  def save(self, *args, **kwargs):
    if not self.pk and not self.tool_id:
      self.tool_id = slugify(self.name + ' ' + secrets.token_hex(nbytes=4))

    if self.logo:
      OptimizeImageField(self.logo, self.LOGO_MINIMUM_DIMENSION)

    return super(Tool, self).save(*args, **kwargs)

  def get_absolute_url(self):
    try:
      url = reverse(self.url_reverser)
    except:
      url = reverse(self.url_reverser, kwargs={'tool_id':self.tool_id})

    return url

  def get_manager_instance(self):
    module_path, class_name = self.manager_class.rsplit('.', 1)
    module = importlib.import_module(module_path)
    cls = getattr(module, class_name)
    return cls()

  @property
  def db_class(self):
    manager_instance = self.get_manager_instance()
    db = manager_instance.get_db_table()
    return db

  def get_db_records(self, user):
    db = self.db_class
    return db and db.list_all(user) or []

  def increase_uses_count(self):
    self.uses_count += 1
    self.save()


class UpcomingTool(models.Model):
  name = models.CharField(max_length=128)
  description = models.TextField()

  upvote = models.IntegerField(blank=True, null=True, default=0)
  downvote = models.IntegerField(blank=True, null=True, default=0)

  active = models.BooleanField(default=False)

  created = models.DateField(auto_now_add=True)
  updated = models.DateField(auto_now=True)

  objects = UpcomingToolManager()

  class Meta:
    indexes = [
      models.Index(fields=['active'], name='upcoming_active_idx')
    ]

  def __str__(self):
    status = emoji.ACTIVE if self.active else emoji.DISABLE
    return f'{self.name} {status}'


class SuggestedTool(models.Model):
  user = models.ForeignKey(User, related_name='user_suggested_tools', on_delete=models.SET_NULL, blank=True, null=True)
  description = models.TextField()

  seen = models.BooleanField(default=False)

  created = models.DateField(auto_now_add=True)
  updated = models.DateField(auto_now=True)

  def __str__(self):
    user = self.user
    username = user.username if user else 'Anonymous' 
    description = self.description[:30]
    status = emoji.SEEN if self.seen else emoji.UN_SEEN

    return f'{self.pk} - {username} {username} ({description}) {status}'


class ToolIssueReport(models.Model):
  tool =  models.ForeignKey(Tool, related_name='tool_issue_reports', on_delete=models.CASCADE)
  user = models.ForeignKey(User, related_name='user_issue_reports', on_delete=models.SET_NULL, blank=True, null=True)
  description = models.TextField()

  seen = models.BooleanField(default=False)

  created = models.DateField(auto_now_add=True)
  updated = models.DateField(auto_now=True)

  def __str__(self):
    user = self.user
    username = user.username if user else 'Anonymous' 
    description = self.description[:30]
    status = emoji.SEEN if self.seen else emoji.UN_SEEN

    return f'{self.pk} - {username} {username} ({description}) {status}'

toolsframe/forms.py
from django import forms
from .models import ToolIssueReport, SuggestedTool



class IssueAndSuggestionFormsMethods:
  def clean_description(self):
    description = self.cleaned_data.get('description')
    length_required = 12

    if len(description.strip()) < length_required:
      raise forms.ValidationError(f'issue description must be more than {length_required} letter!!!')
    return description

  def get_error_message(self):
    return 'description: ' + self.errors['description']


class ToolIssueReportForm(IssueAndSuggestionFormsMethods, forms.ModelForm):
  description = forms.CharField(label='', widget=forms.Textarea(attrs={
    'x-model':'issueDescription',
    'class':'w-full h-32 bg-primary-600 px-3 py-2',
    'placeholder':'Explain...',
    'x-ref':'reportIssueTextarea',
    'x-on:input':'textareaAutoGrow()',
    'style':'max-height: 60vh;',
  }))

  class Meta:
    model = ToolIssueReport
    fields = [ 'description' ]



class SuggestToolForm(IssueAndSuggestionFormsMethods, forms.ModelForm):
  description = forms.CharField(label='', widget=forms.Textarea(attrs={
    'x-model':'toolDescription',
    'class':'h-24 px-3 py-2 border-0 bg-primary-600',
    'placeholder':'Tool description',
    'name':'tool-suggestion',
    'x-ref':'suggestionTextarea',
    'x-on:input':'textareaAutoGrow()',
    'style':'max-height: 390px; height: 84px;',
  }))

  class Meta:
    model = SuggestedTool
    fields = [ 'description' ]

toolsframe/views.py
from django.shortcuts import render
from django.views import View
from django.views.decorators.http import require_http_methods
from django.views.generic.base import TemplateView

from .models import Tool

from utils.views_mixins import GenerateDefaultContext
from utils.mixins import FormSaveMixin
from utils.helpers import Redirector

from .forms import ToolIssueReportForm, SuggestToolForm

from tools.loaders import load_tool_classes
from django.http import HttpResponse


def refresh_tools(request):
  for tool_class in load_tool_classes():
    tool_class().store_in_db()
  return HttpResponse('<h1>Tools refreshed</h1>')



@require_http_methods(['GET'])
def toggle_color_mode(request):
  response = Redirector.go_previous_page(request)
  cookie_name = 'light-mode'
  cookie_exist = request.COOKIES.get(cookie_name, False)

  if cookie_exist: response.delete_cookie(cookie_name)
  else: response.set_cookie(cookie_name, 'true')

  return response

@require_http_methods(['GET'])
def index(request):
  tools = Tool.objects.list_for_homepage()
  context = GenerateDefaultContext(request)

  context.update({ 'tools': tools })

  return render(request, 'd_homepage.html', context)


@require_http_methods(['GET'])
def get_tool_page(request, tool_id):
  tool = Tool.objects.force_get(tool_id=tool_id)
  db_records = tool.get_db_records(request.user)

  context = GenerateDefaultContext(request)
  context.update({
    'tool': tool, 'db_records': db_records, 'issue_form': ToolIssueReportForm()
  })

  Tool.objects.increase_views_count(pk=tool.pk)

  return render(request, 'd_tool-doc.html', context)


class SuggestTool(FormSaveMixin, View):
  form_class = SuggestToolForm

  def update_saved_object(self, request, obj, *args, **kwargs):
    if request.user.is_authenticated:
      obj.user = request.user
    return obj


class ReportToolIssue(FormSaveMixin, View):
  form_class = ToolIssueReportForm

  def update_saved_object(self, request, obj, *args, **kwargs):
    tool_id = kwargs.get('tool_id')
    tool = Tool.objects.force_get(tool_id=tool_id)
    obj.tool = tool

    if request.user.is_authenticated:
      obj.user = request.user
    return obj





class PrivacyPolicyView(TemplateView):
  template_name = "privacy_policy.html"

toolsframe/templates/d_homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% include 'components/head.html' %}

    <title>Ninja-Bag | Homepage</title>
  </head>
  <body>
    {% include 'components/loading-page.html' %}

    <div id="homepage">
      {% include 'components/header.html' %}

      <div class="content flex justify-evenly items-start flex-col sm:flex-row">
        <main class="cards flex flex-wrap justify-evenly items-stretch">
          {% for tool in tools %}
          <div
            class="card mb-6 rounded-lg overflow-hidden relative pb-6 mr-0 sm:mr-4"
          >
            <header class="flex items-center justify-start px-5 py-3">
              {% if tool.logo %}
              <div
                class="w-14 h-14 rounded-full overflow-hidden bg-center bg-cover bg-no-repeat mr-5"
                style="background-image: url({{ tool.logo.url }});"
              ></div>
              {% endif %}

              <div>
                <h3 class="text-xl font-bold capitalize">
                  {{ tool.name|truncatechars:25 }}
                </h3>
              </div>
            </header>

            <div class="content px-5 py-8">
              <div class="overflow-hidden leading-7">
                {{ tool.description|safe|truncatechars:240 }}
              </div>

              <!-- <ul class="flex flex-wrap mt-2">
                {% for category in tool.category.all %}
                <li class="text-sm rounded bg-primary-800 text-primary-300 mr-1 hover:bg-gray-700 hover:text-gray-300 capitalize font-bold">
                  <a class="px-2 py-1 inline-block" href="#">{{ category.name }}</a>
                </li>
                {% endfor %}
              </ul> -->
            </div>

            <footer class="px-5 pt-1 pb-4 absolute bottom-0 right-0 left-0">
              <div class="text-right pt-2">
                <a
                  href="{% url tool.url_reverser tool.tool_id %}"
                  class="button-style text-sm uppercase font-bold px-3 py-2 rounded-lg bg-accent text-button-text"
                >
                  view
                </a>
              </div>
            </footer>
          </div>
          {% endfor %}
        </main>

        <aside class="flex-shrink-0 w-full sm:w-80">
          {% include 'components/aside.html' %}
        </aside>
      </div>

      {% include 'components/footer.html' %}
    </div>
  </body>
</html>

toolsframe/templates/d_tool-doc.html
{% load static %} {% load filters %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% include 'components/head.html' %}

    <title>{{ tool.name|title }} | Ninja-Bag</title>

    {{ tool.endpoints|json_script:"tool-endpoints" }} 
    {{ account.token|json_script:"user-token" }} 
    {{ is_limits_active|json_script:"is-limits-active" }}

    <script>
      const toolIssueUrl = "{% url 'toolsframe:report-tool' tool.tool_id %}"
    </script>

    <script src="{% static 'js/endpoint-handler-classes.js' %}"></script>
  </head>
  <body>
    {% include 'components/loading-page.html' %}

    <div id="api" class="flex flex-col min-h-screen">
      {% include 'components/header.html' %}

      <div class="content flex justify-evenly items-start flex-col md:flex-row grow w-full">
        <main class="flex-grow pr-5 pb-10 w-full">
          {% include 'tool-components/tool-info.html' %}

          {% if tool.login_required and not is_authenticated %}
          <div class="font-bold text-primary-100 text-center">
            <h3 class="text-4xl capitalize">Tool require login</h3>
            <h4 class="text-xl mt-2">Go to <a class="text-accent" href="{% url 'accounts:login-page' %}">login page</a></h4>
          </div>
          {% endif %}

          <div class="end-points">
            <h2 class="text-2xl font-bold capitalize mb-6">endpoints</h2>

            <ul x-data="renderEndpoints()">
              <template x-for="(endpoint, index) in endpoints" :key="index">
                <li class="rounded-lg px-5 py-3 method-get mb-4">
                  {% include 'endpoint-components/ep-basic-info.html' %}

                  <div
                    class="endpoint-full-info props"
                    x-show="endpoint.isOpen"
                  >
                    {% if is_limits_active %} 
                      {% include 'endpoint-components/ep-limits.html' %} 
                    {% endif %}

                    <div class="example py-3">
                      <template x-if="!endpoint.stop_http_testing">
                        <div>
                          <h4 class="text-lg capitalize font-bold mr-3 mb-5">
                            example
                          </h4>

                          <div
                            class="http-request px-5 py-3 rounded-lg bg-primary-800 mb-8"
                          >
                            {% include 'endpoint-components/ep-request-http-syntax.html' %}

                            <div class="mt-4 flex justify-between items-center">
                              <span class="font-bold text-accent">
                                Double click to start update request to try it
                              </span>

                              {% include 'endpoint-components/ep-request-action-buttons.html' %} 
                              {% include 'endpoint-components/ep-request-popup-try.html' %}
                            </div>
                          </div>
                        </div>
                      </template>

                      {% include 'endpoint-components/ep-params.html' %}
                    </div>
                  </div>
                </li>
              </template>
            </ul>
          </div>

          {% if db_records %}
          <div class="db-records mt-8">
            <h2 class="text-2xl font-bold capitalize mb-6">
              tool database records
            </h2>

            <ul class="no-select" x-data="ToolDatabaseRecordsData()">
              {% for record in db_records %}
              <li class="flex justify-between border-b-2 pb-1 mb-2">
                <a href="{{ record.get_absolute_url_read }}">
                  {{ record.file_name }}
                </a>

                <div class="actions">
                  <a
                    class="text-sm font-bold text-primary-200 capitalize mr-2"
                    href="{{ record.get_absolute_url_delete }}"
                    x-on:click.prevent="confirmDelete($event)"
                  >delete</a>

                  <a
                    class="text-sm font-bold text-primary-200 capitalize"
                    href="#"
                    x-on:click.prevent="copyFileName('{{ record.file_name }}')"
                  >copy name</a>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          {% endif %}
        </main>

        <aside class="flex-shrink-0 w-full md:w-80">
          {% include 'components/aside.html' %}
        </aside>
      </div>

      {% include 'components/footer.html' %}
    </div>
  </body>
</html>