accounts/urls.py
from django.urls import path

from .views import index, logout_account

app_name = 'accounts'

urlpatterns = [
  path('', index, name='login-page'),
  path('logout/', logout_account, name='logout'),
]

dj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

from app.views import error_page

import debug_toolbar

handler404 = error_page(404)
handler500 = error_page(500)

urlpatterns = [
  path('', include('social_django.urls', namespace='social')),
  path('logout/', LogoutView.as_view(template_name=settings.LOGOUT_REDIRECT_URL), name='logout'),

  path('', include('toolsframe.urls', namespace='toolsframe')),
  path('t/', include('tools.urls', namespace='tools')),
  path('account/', include('accounts.urls', namespace='accounts')),

  path('admin/', admin.site.urls),
  path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toolsframe/urls.py
from django.urls import path

from .views import index, get_tool_page, SuggestTool, ReportToolIssue, toggle_color_mode, refresh_tools, PrivacyPolicyView

app_name = 'toolsframe'

urlpatterns = [
  path('refresh/', refresh_tools, name='xxx'),

  path('', index, name='homepage'),
  path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),

  path('toggle-color-mode/', toggle_color_mode, name='toggle-color'),
  path('tool/<str:tool_id>/', get_tool_page, name='tool'),
  path('suggest-tool/', SuggestTool.as_view(), name='suggest-tool'),
  path('report-tool/<str:tool_id>/', ReportToolIssue.as_view(), name='report-tool')
]

toolsframe/models.py
import importlib
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.text import slugify

from utils import emoji
from utils.mixins import OptimizeImageField

import secrets

from .managers import  (
  UpcomingToolManager,
  ToolManager
)

User = get_user_model()

class Category(models.Model):
  name = models.CharField(max_length=128)

  created = models.DateField(auto_now_add=True)
  updated = models.DateField(auto_now=True)

  class Meta:
    verbose_name = 'Category'
    verbose_name_plural = 'Categories'

  def __str__(self):
    return self.name

  @property
  def tools(self):
    return self.category_tools.all()


class Tool(models.Model):
  LOGO_MINIMUM_DIMENSION = 170
  # required
  name = models.CharField(max_length=128)
  app_type = models.CharField(max_length=32) # api || web based
  tool_id = models.CharField(max_length=128, unique=True, editable=False, blank=True, db_index=True)
  logo = models.ImageField(upload_to='tool_logo', blank=True, null=True)
  description = models.TextField(blank=True, null=True) # SEO && after title
  url_reverser = models.CharField(max_length=64, default='toolsframe:tool') # 'app_name:home'
  endpoints = models.JSONField(blank=True, null=True)
  manager_class = models.CharField(max_length=64, blank=True, null=True)

  category = models.ManyToManyField(Category, related_name='category_tools')

  login_required = models.BooleanField(default=False)
  active = models.BooleanField(default=True, db_index=True)
  has_db = models.BooleanField(default=False)

  uses_count = models.IntegerField(default=0)
  views_count = models.IntegerField(default=0)

  created = models.DateField(auto_now_add=True)
  updated = models.DateField(auto_now=True)

  objects = ToolManager()

  class Meta:
    verbose_name = 'Tool'
    verbose_name_plural = 'Tools'

  def __str__(self):
    status = emoji.ACTIVE if self.active else emoji.DISABLE
    return f'{self.pk}- {self.tool_id} {status}{" | NoImage" if not self.logo else ""}'

  def save(self, *args, **kwargs):
    if not self.pk and not self.tool_id:
      self.tool_id = slugify(self.name + ' ' + secrets.token_hex(nbytes=4))

    if self.logo:
      OptimizeImageField(self.logo, self.LOGO_MINIMUM_DIMENSION)

    return super(Tool, self).save(*args, **kwargs)

  def get_absolute_url(self):
    try:
      url = reverse(self.url_reverser)
    except:
      url = reverse(self.url_reverser, kwargs={'tool_id':self.tool_id})

    return url

  def get_manager_instance(self):
    module_path, class_name = self.manager_class.rsplit('.', 1)
    module = importlib.import_module(module_path)
    cls = getattr(module, class_name)
    return cls()

  @property
  def db_class(self):
    manager_instance = self.get_manager_instance()
    db = manager_instance.get_db_table()
    return db

  def get_db_records(self, user):
    db = self.db_class
    return db and db.list_all(user) or []

  def increase_uses_count(self):
    self.uses_count += 1
    self.save()


class UpcomingTool(models.Model):
  name = models.CharField(max_length=128)
  description = models.TextField()

  upvote = models.IntegerField(blank=True, null=True, default=0)
  downvote = models.IntegerField(blank=True, null=True, default=0)

  active = models.BooleanField(default=False)

  created = models.DateField(auto_now_add=True)
  updated = models.DateField(auto_now=True)

  objects = UpcomingToolManager()

  class Meta:
    indexes = [
      models.Index(fields=['active'], name='upcoming_active_idx')
    ]

  def __str__(self):
    status = emoji.ACTIVE if self.active else emoji.DISABLE
    return f'{self.name} {status}'


class SuggestedTool(models.Model):
  user = models.ForeignKey(User, related_name='user_suggested_tools', on_delete=models.SET_NULL, blank=True, null=True)
  description = models.TextField()

  seen = models.BooleanField(default=False)

  created = models.DateField(auto_now_add=True)
  updated = models.DateField(auto_now=True)

  def __str__(self):
    user = self.user
    username = user.username if user else 'Anonymous' 
    description = self.description[:30]
    status = emoji.SEEN if self.seen else emoji.UN_SEEN

    return f'{self.pk} - {username} {username} ({description}) {status}'


class ToolIssueReport(models.Model):
  tool =  models.ForeignKey(Tool, related_name='tool_issue_reports', on_delete=models.CASCADE)
  user = models.ForeignKey(User, related_name='user_issue_reports', on_delete=models.SET_NULL, blank=True, null=True)
  description = models.TextField()

  seen = models.BooleanField(default=False)

  created = models.DateField(auto_now_add=True)
  updated = models.DateField(auto_now=True)

  def __str__(self):
    user = self.user
    username = user.username if user else 'Anonymous' 
    description = self.description[:30]
    status = emoji.SEEN if self.seen else emoji.UN_SEEN

    return f'{self.pk} - {username} {username} ({description}) {status}'

toolsframe/forms.py
from django import forms
from .models import ToolIssueReport, SuggestedTool



class IssueAndSuggestionFormsMethods:
  def clean_description(self):
    description = self.cleaned_data.get('description')
    length_required = 12

    if len(description.strip()) < length_required:
      raise forms.ValidationError(f'issue description must be more than {length_required} letter!!!')
    return description

  def get_error_message(self):
    return 'description: ' + self.errors['description']


class ToolIssueReportForm(IssueAndSuggestionFormsMethods, forms.ModelForm):
  description = forms.CharField(label='', widget=forms.Textarea(attrs={
    'x-model':'issueDescription',
    'class':'w-full h-32 bg-primary-600 px-3 py-2',
    'placeholder':'Explain...',
    'x-ref':'reportIssueTextarea',
    'x-on:input':'textareaAutoGrow()',
    'style':'max-height: 60vh;',
  }))

  class Meta:
    model = ToolIssueReport
    fields = [ 'description' ]



class SuggestToolForm(IssueAndSuggestionFormsMethods, forms.ModelForm):
  description = forms.CharField(label='', widget=forms.Textarea(attrs={
    'x-model':'toolDescription',
    'class':'h-24 px-3 py-2 border-0 bg-primary-600',
    'placeholder':'Tool description',
    'name':'tool-suggestion',
    'x-ref':'suggestionTextarea',
    'x-on:input':'textareaAutoGrow()',
    'style':'max-height: 390px; height: 84px;',
  }))

  class Meta:
    model = SuggestedTool
    fields = [ 'description' ]

toolsframe/views.py
from django.shortcuts import render
from django.views import View
from django.views.decorators.http import require_http_methods
from django.views.generic.base import TemplateView

from .models import Tool

from utils.views_mixins import GenerateDefaultContext
from utils.mixins import FormSaveMixin
from utils.helpers import Redirector

from .forms import ToolIssueReportForm, SuggestToolForm

from tools.loaders import load_tool_classes
from django.http import HttpResponse


def refresh_tools(request):
  for tool_class in load_tool_classes():
    tool_class().store_in_db()
  return HttpResponse('<h1>Tools refreshed</h1>')



@require_http_methods(['GET'])
def toggle_color_mode(request):
  response = Redirector.go_previous_page(request)
  cookie_name = 'light-mode'
  cookie_exist = request.COOKIES.get(cookie_name, False)

  if cookie_exist: response.delete_cookie(cookie_name)
  else: response.set_cookie(cookie_name, 'true')

  return response

@require_http_methods(['GET'])
def index(request):
  tools = Tool.objects.list_for_homepage()
  context = GenerateDefaultContext(request)

  context.update({ 'tools': tools })

  return render(request, 'd_homepage.html', context)


@require_http_methods(['GET'])
def get_tool_page(request, tool_id):
  tool = Tool.objects.force_get(tool_id=tool_id)
  db_records = tool.get_db_records(request.user)

  context = GenerateDefaultContext(request)
  context.update({
    'tool': tool, 'db_records': db_records, 'issue_form': ToolIssueReportForm()
  })

  Tool.objects.increase_views_count(pk=tool.pk)

  return render(request, 'd_tool-doc.html', context)


class SuggestTool(FormSaveMixin, View):
  form_class = SuggestToolForm

  def update_saved_object(self, request, obj, *args, **kwargs):
    if request.user.is_authenticated:
      obj.user = request.user
    return obj


class ReportToolIssue(FormSaveMixin, View):
  form_class = ToolIssueReportForm

  def update_saved_object(self, request, obj, *args, **kwargs):
    tool_id = kwargs.get('tool_id')
    tool = Tool.objects.force_get(tool_id=tool_id)
    obj.tool = tool

    if request.user.is_authenticated:
      obj.user = request.user
    return obj





class PrivacyPolicyView(TemplateView):
  template_name = "privacy_policy.html"

toolsframe/templates/components/aside.html
{% load filters %}

<div class="acc-info rounded-lg">
  {% if is_authenticated %}
  <div class="user px-5 py-3 flex flex-col items-center">
    <div
      class="w-24 h-24 mb-3 rounded-full overflow-hidden bg-center bg-cover bg-no-repeat"
      style="background-image: url({{ account.get_user_picture }});"
    ></div>
    <h2 class="text-2xl font-bold capitalize">{{ account.get_user_name }}</h2>
  </div>

  {% if is_limits_active %}
  <div class="limitation-progress px-5 py-3 text-sm font-bold">
    <div class="limit mb-6">
      <div class="mb-1 flex justify-between items-center">
        <span class="capitalize">storage</span>
        <span
          >{{ account.get_user_folder_size|to_int }}/{{ account.storage_allowed
          }}</span
        >
      </div>
      <div class="progress-bar w-full h-2 rounded-lg overflow-hidden">
        <div
          class="h-full"
          style="width: {{ account.get_user_folder_size|percent_of:account.storage_allowed }}%;"
        ></div>
      </div>
    </div>

    <div class="limit mb-6">
      <div class="mb-1 flex justify-between items-center">
        <span class="capitalize">bandwidth</span>
        <span
          >{{ account.bandwidth_used|to_int }}/{{ account.bandwidth_allowed
          }}</span
        >
      </div>
      <div class="progress-bar w-full h-2 rounded-lg overflow-hidden">
        <div
          class="h-full"
          style="width: {{ account.bandwidth_used|percent_of:account.bandwidth_allowed }}%;"
        ></div>
      </div>
    </div>
    <div class="limit mb-6">
      <div class="mb-1 flex justify-between items-center">
        <span class="capitalize">requests</span>
        <span
          >{{ account.requests_used|to_int }}/{{ account.requests_allowed
          }}</span
        >
      </div>
      <div class="progress-bar w-full h-2 rounded-lg overflow-hidden">
        <div
          class="h-full"
          style="width: {{ account.requests_used|percent_of:account.requests_allowed }}%;"
        ></div>
      </div>
    </div>
  </div>
  {% endif %}

  <div class="mx-5" x-data="{}">
    <h4 class="capitalize font-bold mb text-sm mb-1">Token</h4>
    <div
      class="bg-primary-800 flex items-center justify-between py-3 px-3 mb-5 rounded-lg"
    >
      <span class="flex-shrink mr-5 overflow-hidden" x-ref="tokenValue"
        >{{ account.token }}</span
      >
      <button
        @click="copyToClipboard($refs.tokenValue.innerText); notify('copied', 'success')"
        class="bg-accent text-button-text px-3 py-1 font-bold uppercase text-xs"
      >
        copy
      </button>
    </div>
  </div>

  <div class="note px-5 pb-3">
    <span
      class="font-bold text-xs px-2 py-1 inline-block text-button-text uppercase"
      >note</span
    >
    You can add token to your request just by pass it throw url
    "token=&lt;value&gt;"
  </div>
  {% endif %}

  {% if is_limits_active %}
  <div class="note px-5 py-3">
    <span
      class="font-bold text-xs px-2 py-1 inline-block text-button-text uppercase"
      >note</span
    >
    unfortunately, i needed to create this limitation because the server
    resources are limited and i wanna to serve as many people as i can so i
    found the limitation is fair enough to satisfy all of us
  </div>
  {% else %}

  <div class="note px-5 py-3">
    <span
      class="font-bold text-xs px-2 py-1 inline-block text-button-text uppercase"
      >note</span
    >
    Ninja bag is free and we hope to remain so. In case we need more server resources, we may apply some limits on it to make a fair use between the users, hope you good time ❤️
  </div>
  {% endif %}
</div>

{% if db_tools %}
<div class="upcoming-tools rounded-lg">
  <h2 class="text-2xl capitalize font-bold mb-3 px-5 py-3">
    Your Databases
  </h2>

  <ul>
    {% for db_tool, is_tool_has_new_records in db_tools %}
    <li class="upcoming-tool hover:bg-gray-700 cursor-default">
      <a
        class="flex relative px-5 py-3 z-0"
        href="{{ db_tool.get_absolute_url }}"
      >
        {% if is_tool_has_new_records %}
        <div
          class="notification-dot absolute right-3 top-3 w-3 h-3 bg-accent rounded-full"
        ></div>
        {% endif %} {% if db_tool.logo %}
        <div
          class="w-10 h-10 mr-2 rounded-full overflow-hidden flex-shrink-0 bg-center bg-cover bg-no-repeat"
          style="background-image: url({{ db_tool.logo.url }});"
        ></div>
        {% endif %}

        <div>
          <h3 class="text-xl font-bold mb-2">{{ db_tool.name }}</h3>
          <p class="">{{ db_tool.description|safe|truncatechars:100 }}</p>
        </div>
      </a>
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %} {% if upcoming_tools %}
<div class="upcoming-tools rounded-lg">
  <h2 class="text-2xl capitalize font-bold mb-3 px-5 py-3">upcoming tools</h2>

  <ul>
    {% for upcoming_tool in upcoming_tools %}
    <li class="upcoming-tool px-5 py-3 hover:bg-gray-700 cursor-default">
      <h3 class="text-xl font-bold mb-2">{{ upcoming_tool.name }}</h3>
      <p class="">{{ upcoming_tool.description }}</p>
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %}

<div class="tool-suggestion rounded-lg">
  <h2 class="text-2xl capitalize font-bold mb-3 px-5 py-3">suggest tool</h2>
  <p class="px-5">Any needed other tool contact us.</p>

  <form
    x-data="toolSuggestionData()"
    class="flex flex-col items-stretch px-5 py-5"
    @submit.prevent="submitToolSuggestion()"
  >
    {{ suggest_form }}

    <button
      style="height: 35px"
      class="mt-3 overflow-hidden font-bold uppercase bg-accent text-button-text"
      x-bind:disabled="isButtonLoading"
      x-bind:class="isButtonLoading ? 'relative' : ''"
      x-html="isButtonLoading ? buttonStates.loading : buttonStates.normal"
    ></button>
  </form>
</div>

toolsframe/templates/components/footer.html
<footer class="p-8">
  <div class="text-center" x-data="getFooterData()" x-html="getPhrase()"></div>
</footer>

toolsframe/templates/components/head.html
{% load static %}
{% load filters %}


<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" media="screen" href="{% if request %}{{request.scheme}}://{{request.META.HTTP_HOST}}{% else %}http://ninja-bag.devmhmd.com{% endif %}{% static 'css/all-style.css' %}">

{% if is_light_mode %}
<link rel="stylesheet" media="screen" href="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'css/light-mode.min.css.css' %}">
{% endif %}

<link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'favicon/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
<meta name="theme-color" content="#ffffff">



<script>
  const suggestToolUrl = `{% url 'toolsframe:suggest-tool' %}`
</script>


<script src="{{request.scheme}}://{{request.META.HTTP_HOST}}{% static 'js/all-script.js' %}" defer></script>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
<script defer data-domain="ninja-bag.devmhmd.com" data-endpoint="https://analytics.make.to/events" src="https://scripts.makeanalyticscdn.com/latest.js"></script>

toolsframe/templates/components/header.html
<header class="flex justify-between items-center relative">
  <div></div>
  <a href="{% url 'toolsframe:homepage' %}" class="logo" title="Homepage">
    {% include 'components/logo.html' %}
  </a>
  <div class="w-0 relative">
    <ul
      class="flex items-center absolute right-0"
      style="top: 50%; transform: translateY(-50%)"
    >
      <li>
        <a
          class="px-3 py-1 capitalize font-bold hover:underline mr-2"
          href="{% url 'toolsframe:homepage' %}"
          title="Homepage"
          >home</a
        >
      </li>
      <li>
        <a
          class="px-3 py-1 capitalize font-bold hover:underline mr-2 whitespace-nowrap hidden md:block"
          href="{% url 'toolsframe:toggle-color' %}"
          title="change color mode"
          >toggle-color</a
        >
      </li>

      {% if is_authenticated %}
      <li>
        <a
          class="px-3 py-1 capitalize font-bold hover:underline"
          href="{% url 'accounts:logout' %}"
          title="Logout"
          >logout</a
        >
      </li>
      {% else %}
      <li>
        <a
          class="px-3 py-1 capitalize font-bold hover:underline"
          href="{% url 'accounts:login-page' %}"
          title="Login"
          >login</a
        >
      </li>
      {% endif %}
    </ul>
  </div>
</header>

toolsframe/templates/components/loading-page.html
<div
  class="loading-page fixed inset-0 bg-primary-800 transition-opacity opacity-100"
>
  <div
    class="lds-ripple"
    style="top: 50%; left: 50%; transform: translate(-50%, -50%)"
  >
    <div></div>
    <div></div>
  </div>
  <style>
    .loading-page + [id] {
      opacity: 0;
      transition: opacity 0.4s ease-in-out;
    }
  </style>
  <script>
    document.addEventListener("DOMContentLoaded", () => {
      const loadingElm = document.querySelector(".loading-page");
      const pageRoot = document.querySelector(".loading-page + [id]");

      setTimeout(() => {
        pageRoot.style.opacity = "1";
        loadingElm.style.opacity = "0";

        setTimeout(() => {
          loadingElm.remove();
        }, 1000);
      }, 1000);
    });
  </script>
</div>

toolsframe/templates/components/logo.html
<div class="logo flex justify-center items-center flex-col">
  <div class="ninja bg-primary-100">
    <div class="eyes bg-primary-600 w-full flex justify-around items-center">
      <div class="eye bg-primary-100"></div>
      <div class="eye bg-primary-100"></div>
    </div>
  </div>
  <div class="site-name text-primary-100 font-bold hidden sm:block mt-1">
    Ninja Bag
  </div>
</div>